# Generated by Django 4.1.4 on 2023-01-05 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movierecommenderapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="show",
            old_name="Actors",
            new_name="actors",
        ),
        migrations.RenameField(
            model_name="show",
            old_name="Director",
            new_name="director",
        ),
        migrations.RenameField(
            model_name="show",
            old_name="Poster",
            new_name="poster",
        ),
        migrations.RenameField(
            model_name="show",
            old_name="Runtime",
            new_name="runtime",
        ),
    ]
