# Generated by Django 4.1.4 on 2023-01-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommenderapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='show_id',
            new_name='show',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='show_id',
            new_name='show',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user',
        ),
    ]
